### PR TITLE
SASL/SCRAM authentication

### LINKED ISSUE #1508: Unknown authenticationOk message type
With postgres 10.1 and SCRAM-SHA-256 password encryption enabled, node-postgres driver throws the following error:

`Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }`

Not telling that encryption method is not supported or anything. It took a while to find out why my app is stopped working after i have changed the role name. I think there should be more verbose error for this case.

### PR DESCRIPTION
**Pull request by andreme**
Fixes #1508

Adapted from:
https://github.com/npgsql/npgsql/blob/8bf421979b4b19cd63e25ecec3f0e1804871700a/src/Npgsql/NpgsqlConnector.Auth.cs
https://github.com/legastero/js-sasl-scram-sha-1
https://github.com/czzarr/node-bitwise-xor

### CODE REVIEW

File: test/integration/client/scram-tests.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
+'use strict'
```
Comment (andreme) [inline test/integration/client/scram-tests.js]: I'm not sure how this can be integrated into the test run? The role needs to be created with a scram-sha-256 password

**Comment by andreme** [comment]
I don't have make, so I've only run the tests added/changed by me

**Comment by andreme** [comment]
The failing test for node 11 fails in other pr's too, so I assume it's not something I did

**Comment by brianc** [comment]
ohh very very nice.

**Comment by brianc** [comment]
Hey if you rebase on master now the test should pass!

**Comment by andreme** [comment]
@brianc thanks, rebased

**Comment by demisx** [comment]
Can this please be merged? We are stuck because of #1508 right now. Thank you!

**Comment by brianc** [comment]
yup! Will look @ this today. Apologies for the delay!

**Comment by brianc** [comment]
@andreme this is really awesome!  Thanks a lot for taking the time on this.  Do you have any documentation on how to get the integration test to pass? I'd like to at least be able to run the integration test locally & once I figure that out I'll work out how to add a hook to run it in CI (if possible).  Since it's auth related I'd really like to get this running "end-to-end" in tests so we can be sure we don't regress on this at any point.  I think I need postgres@11.x at least...anything else I need to do?  I'll see how much I can modify the postgres hba

**Comment by andreme** [comment]
@brianc pg10 is the first version that has scram auth.
Basically, the setup is creating a user with a scram encrypted password, and adding the entries in the pg_hba for that user with scram auth. The template for that is in the test file.

Make sure the user entries come before any trust entries in the pg_hba.

**Comment by brianc** [comment]
gotcha! 

> Make sure the user entries come before any trust entries in the pg_hba.

good point. will do.

I'll start trying to get the CI stuff working today so we can merge this thing!

**Comment by brianc** [comment]
I'm going to merge this but hold off on releasing semver minor w/ this feature until I can get some tests running in CI.  Reading about setting up postgres-10 in travis & configuring pg_hba.conf and stuff now...will hopefully have it set up today.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
