### PR TITLE
Queued query errors

### LINKED ISSUE #1454: Fails to error on queries inside a transaction after a lost connection
When we execute a lengthy operation inside a transaction, and the connection is suddenly lost during that time, then any query we execute on the `client` after that become stuck, i.e. they report nether success no error:

```js
'use strict';

const Pool = require('pg-pool');

const cn = {
    database: 'newone',
    port: 5433,
    user: 'postgres'
};

const p = new Pool(cn);

p.on('error', error => {
    // do nothing
});

p.connect((err, client, release) => {
    if (err) {
        console.log('Failed to connect:', err);
        return;
    }
    const test = async function () {
        try {
            await client.query('BEGIN');
            await client.query('SELECT pg_sleep(10)'); // connection breaks during this one
            await client.query('COMMIT');
            console.log('success!');
        } catch (e) {
            console.log('about to rollback...'); // this is reported
            await client.query('ROLLBACK'); // this one is stuck, never reporting an error, if the error was due to lost connection
            console.log('rollback finished'); // this is never reported, if we are here because of lost connection
        } finally {
            release();
            p.end();
        }
    };

    test();
});
```

I've tried both `pg-pool` directly and via `node-postgres`, versions 6.x and 7.x - all the same.

**Expected Behavior**

Executing any query against `client` at that point should immediately report an error that informs us of the lost connectivity.

### PR DESCRIPTION
**Pull request by charmander**
> Separates socket errors from error messages, sends socket errors to all queries in the queue, marks clients as unusable after socket errors.
>
> This is not very pleasant but should maintain backwards compatibility…?

I don’t know if this is how you want to handle the issue, but it should address #1454 and #632.

Maybe in a future version the query queue and clients pending `connect()` won’t need to exist at all?

### CODE REVIEW

**Comment by charmander** [comment]
(Tests are failing because this is missing the changes for lib/native. Does it still offer a significant performance advantage, by the way?)

**Comment by rkaw92** [comment]
Hi, just read your test case. Can you please test with two or more queries after the connection is downed? As reported in #1500 , the first query after the connection fails was already emitting an error. It was the *second* query that was locked forever.

https://gist.github.com/rkaw92/9cbd71fdb98d74f01c624bb2a003cd2a#file-client-query-disconnect-js

File: lib/query.js [hunk 1]
```diff
@@ -147,22 +147,17 @@ Query.prototype.handleError = function (err, connection) {
 
 Query.prototype.submit = function (connection) {
   if (typeof this.text !== 'string' && typeof this.name !== 'string') {
-    const err = new Error('A query must have either text or a name. Supplying neither is unsupported.')
-    connection.emit('error', err)
-    connection.emit('readyForQuery')
-    return
+    return new Error('A query must have either text or a name. Supplying neither is unsupported.')
```
Comment (rkaw92) [inline lib/query.js]: Returning an error doesn't seem like a widely-used practice. Why are we not throwing it?

Comment (charmander) [reply lib/query.js]: It would have to be caught to be passed to the callback and it wouldn’t be easy to distinguish from other errors at that point.

**Comment by charmander** [comment]
@rkaw92 In your case, the connection was terminated between queries. In the test, the connection is terminated during the first query, and there is no subsequent `readyForQuery` message.

File: lib/query.js (hunk 1 above)
Comment (rkaw92) [reply lib/query.js]: Now that you mention it, do we need to distinguish it from other errors? Reporting an error that occurred in the stack when calling Query.submit as a "query error" sounds rather intuitive.

Comment (charmander) [reply lib/query.js]: There shouldn’t be any other errors so I prefer not to treat those like they’re expected if they do occur.

File: lib/client.js [hunk 2]
```diff
@@ -389,25 +422,36 @@ Client.prototype.query = function (config, values, callback) {
     query._result._getTypeParser = this._types.getTypeParser.bind(this._types)
   }
 
+  if (!this._queryable) {
+    query.handleError(new Error('Client has encountered a connection error and is not queryable'), this.connection)
+    return
```
Comment (rkaw92) [inline lib/client.js]: Returning `undefined` causes breakage for Promise users when calling `.query()` after the connection has gone down. Should return `result` instead.

Comment (charmander) [reply lib/client.js]: Thanks!

**Comment by rkaw92** [comment]
Something is not quite right, still. Tested with my original gist:
* The first query after the failing connection does reject with an error - however:
* The second query after the failing connection encounters `!this._queryable` and this causes an invalid return (which you've now fixed just a moment ago).

It appears I was wrong in my initial assessment of the sequence of events in case the connection goes down (ends) between queries (`activeQuery === null`) - at the time the connection ends (assuming it goes down gracefully, i.e. TCP RST, no timeout), there is no immediate `error` event, just an `end`. Here's what happens with the code from your branch:
* Connection ends, emitting an `end` event
* The `con.once('end', ...)` handler fires
  * `error` event is emitted on the Client object
* Note that there was no `error` event on the actual *connection* object, nor an `errorMessage` (because the connection just went away without sending us anything)
  * We still have not entered `connectedErrorMessageHandler` nor `connectedErrorHandler`
* User fires **query1** - this does not trip the `!this.queryable` check so we go forward and post the query to the connection stream
* Now we get a real `error` from the stream (because we tried to `write()` to it), so we run `connectedErrorHandler` and it sets `this.queryable` to false. Since a query is active, it gets a legit promise rejection.
* User fires **query2** - this time, the `!this.queryable` check causes an early exit.

After your `return` fix, it seems like the whole thing should work, but it may be a bit surprising to users that the first query after the connection goes down behaves differently than the second one (i.e. different error). What do you think?

**Comment by charmander** [comment]
I think a user should be checking error codes if they expect certain types of errors and not sending a second query after the connection failed. The `end` listener for the `Connection` not setting `_queryable = false` is an oversight, though.

**Comment by rkaw92** [comment]
Nice. All queries are now receiving the same error in the scenario from my gist.

**Comment by charmander** [comment]
@brianc, is the right way to implement this for pg-native to change https://github.com/brianc/node-pg-native/blob/25d12eb2a26d10a8c32036acf19253e131c266f5/index.js#L208 to a query error and all other errors to fatal errors?

**Comment by brianc** [comment]
@charmander - yah I think so.  I know it's kinda a pain to have to go change something over in `pg-native` and the over here as well. :( Maybe one day we can combine things into a monorepo and use yarn workspaces or something to manage it.  Thanks for doing this by the way - this is awesome. :hugs:

**Comment by rkaw92** [comment]
Guys, where are we on this? Any roadblocks?

**Comment by brianc** [comment]
@charmander I updated pg-native w/ the breaking change to emit errors more regularly [here](https://github.com/brianc/node-pg-native/pull/64).  Looks like the tests are still failing here for some reason.

**Comment by charmander** [comment]
@brianc Tests fixed. Thanks for all the work today!

**Comment by brianc** [comment]
Ah nice! I'll merge this tonight, put together a final release for the 7.x branch, and the major version bump for the small change to not being able to call `pg.Pool()` without the new keyword from #1541

**Comment by aelath** [comment]
👋Wanted to check in on progress of this PR. I've been following an issue around (#1105) and I think this PR *might* fix our issues we are seeing in production. When do you expect to merge this? Thanks!

**Comment by charmander** [comment]
@brianc ^?

**Comment by vitaly-t** [comment]
@brianc What happened here? Why wasn't it merged?

@charmander

**Comment by vitaly-t** [comment]
Something makes my scratch my head in these changes....

It removed the `callback` verification inside `Client.prototype._connect`, presuming that the value is always set, since the method is always called from `Client.prototype.connect`.

However, the internal method sets `callback` to `null`, just as it receives `readyForQuery` notification: https://github.com/brianc/node-postgres/blob/3828aa86081491282c118884c245b4a19619f02e/lib/client.js#L181

And since the callback was replaced to use `nextTick`, it is now entirely possible that when we get inside that tick, event `readyForQuery` has already fired, and then calling unverified `callback()` inside the tick will throw an error, pending a race condition.

**Comment by brianc** [comment]
yeah that might be possible - could you write a failing test for this? I'll fix it in a PR if you can reproduce.

**Comment by vitaly-t** [comment]
@brianc That's the known specific of race conditions, they are almost impossible to test in a controlled environment. I don't think I can create one, sorry.

**Comment by brianc** [comment]
I thought about this a bit more - I don't think its possible.  Each call to `client.connect` creates a new function scope.  If this 'error you have already used this client' error fires it will never reach the point in the code where `readyForQuery` is fired, and vise versa.  It's also not reproducible even through manually firing `readyForQuery` or manipulating the event listener collection on `client.connection`.

**Comment by brianc** [comment]
and checking for `if(callback)` is no longer actually needed in the `_connect` function because if the `client.connect` function is called without a callback it now returns a promise, which rejects, and either way `_connect` is _always_ called with a callback function (either user supplied or the callbackified promise handler)

**Comment by vitaly-t** [comment]
Ok, I trust you this, but time will tell, if there is any issue there :wink:

Ans in the second post you referred to what I was describing myself, but the issue I mentioned was that internally `callback` is set to `null`, and since `nextTick` is asynchronous, a race condition seemed possible.
